//@version=5

indicator(title = "52 Weeks Highs-Lows S&P 500 - Mugur", shorttitle="52 Weeks Highs-Lows S&P 500")

newhigh = request.security ("MAHP", "", close)
newlow = request.security ("MALP", "", close)
draw = newhigh - newlow

plot(0, title="Zero Line", color = color.yellow, linewidth=1, style=plot.style_line, editable=false, display=display.all)
//plot(500, title="500 Line", color = color.green, linewidth=1, style=plot.style_line, editable=false, display=display.all)
//plot(-500, title="-500 Line", color = color.red, linewidth=1, style=plot.style_line, editable=false, display=display.all)

plot(draw, title="New Highs-Lows", color = draw>=0?color.green:color.red, style=plot.style_columns, linewidth=2)
